/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	QueryRoot:{
		room:{
			id:{
				type:"RoomId",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	RoomObject:{
		tickets:{
			secret:{
				type:"Secret",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		ticket:{
			id:{
				type:"TicketId",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		isSecret:{
			secret:{
				type:"Secret",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	RoomId: "String",
	Secret: "String",
	TicketId: "String",
	MutationRoot:{
		enterQueue:{
			roomId:{
				type:"RoomId",
				array:false,
				arrayRequired:false,
				required:true
			},
			body:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		leaveQueue:{
			roomId:{
				type:"RoomId",
				array:false,
				arrayRequired:false,
				required:true
			},
			ticketId:{
				type:"TicketId",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		setHelp:{
			roomId:{
				type:"RoomId",
				array:false,
				arrayRequired:false,
				required:true
			},
			ticketId:{
				type:"TicketId",
				array:false,
				arrayRequired:false,
				required:true
			},
			secret:{
				type:"Secret",
				array:false,
				arrayRequired:false,
				required:true
			},
			help:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		setOpen:{
			roomId:{
				type:"RoomId",
				array:false,
				arrayRequired:false,
				required:true
			},
			secret:{
				type:"Secret",
				array:false,
				arrayRequired:false,
				required:true
			},
			open:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	}
}

export const ReturnTypes: Record<string,any> = {
	QueryRoot:{
		rooms:"RoomObject",
		room:"RoomObject"
	},
	RoomObject:{
		id:"RoomId",
		tickets:"TicketObject",
		ticket:"TicketObject",
		isSecret:"Boolean",
		isOpen:"Boolean"
	},
	TicketObject:{
		id:"TicketId",
		body:"String",
		status:"TicketStatus"
	},
	TicketStatus:{
		position:"Int",
		isBeingHelped:"Boolean",
		isInQueue:"Boolean"
	},
	MutationRoot:{
		createRoom:"CreateRoomResponse",
		enterQueue:"TicketObject",
		leaveQueue:"Boolean",
		setHelp:"Boolean",
		setOpen:"Boolean"
	},
	CreateRoomResponse:{
		roomId:"RoomId",
		secret:"Secret"
	}
}